version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: diyhue_server_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  server:
    image: diyhue/core:latest
    restart: on-failure
    network_mode: host
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/data:/opt/hue-emulator/config
      - /run/dbus:/run/dbus:ro
    environment:
      - PUID=1000
      - PGID=1000