version: "3.7"

services:
  server:
    image: diyhue/core:latest
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/config:/opt/hue-emulator/config
      - /run/dbus:/run/dbus:ro
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - '80:80'
      - '443:443'
      - '1900:1900/udp'
      - '2100:2100/udp'
      - '1982:1982/udp'
